[package]
name = "cabide"
version = "0.1.0"
authors = ["Paulo Cabral Sanz <paulosanz@poli.ufrj.br>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
#bincode = "1"
serde_json = "1"

[dev-dependencies]
rand = "0.7"
